### For this Midterm exam we will be coding a little navigation program. Typically, a good navigation program is pretty complex with thousands of variables that need to be taken into account. We will do a simplified case where a traveler can only travel between 12 cities, on predetermined routes. Your task will be to let the driver know how long their trip will be and what the best route is when they want to go from A to B. 

### Problems to Hand In: Your log is part of your Midterm exam. In one of the entries, it should identify the start and end of the Midterm and list the problem numbers in order. Keep notes about what you are doing for each problem, as well as the answers to the problems. 


<img src="octodriver.png" width=300 height=300 />

## ----------------------------- 
## Problem 1 (5 points total). 

### A) (2 points) Start by making a new folder under HW/ called Midterm/.  Your main homework file is this Jupyter notebook. Remember to rename it to midterm_$\mathrm{<username>}$.ipynb.  Save it under Midterm/ . Remember to commit your file often and push to GitHub. Note that Github also serves as a great backup and will help you to submit *something* if an unexpected problem appears before the deadline (e.g., your laptop breaks). We will check this as part of your grading!

### Your name, assignment number, and the date should appear as comments at the top using markdown. Any remarks or written answers you may make should be written using Markdown. If you need to comment something in the code (for clarity) do so with a normal comment. Use the print() function to print, don’t just type the expression. 

Logan Garcia

10/19/2022

PHZ3150 Midterm

### B) (3 points). For this program you will need the numerical module of Python. Do the appropriate import.


In [8]:
import numpy as np

## -----------------------------
## Problem 2 (20 points total).  Let’s start our program! 

### A) (4 points) We need to inform the user of our navigation system that we need from them a start and ending point for their trip. Print an informative sentence that lets the user know that we need them to input two cities (start_city, target_city). Their available options should be: Atlanta, Baltimore, Boston, Charlotte, Dallas, Denver, Jacksonville, Minneapolis, Orlando, Sacramento, Tampa and Washington (let the user know this!). 

<img src="map_part.png" width=500 height=350 />
Caption: Google maps screenshot of a part of the cities that your traveler can go from/to. Not included for clarity are Sacramento and Minneapolis.

In [2]:
print("Thank You for using our system, please input a start city and target city down below.")

Thank You for using our system, please input a start city and target city down below.


### B) (4 points) Ask the input start_city and target_city for your trip

In [3]:
#Takes the city the user wants to start at
start_city = input("\nEnter the City where you want to start your trip from:").capitalize()


Enter the City where you want to start your trip from:Paris


In [4]:
#Takes the city the user wants to go to
target_city = input("\nEnter the city name where you want to reach:").capitalize()


Enter the city name where you want to reach:Orlando


### C) (4 points) Make a list cities_list with all the names of the possible cities the traveler can go from/to.

In [2]:
cities_list = ["Atlanta", "Baltimore", "Boston", "Charlotte", "Dallas", "Denver","Miami", "Minneapolis", "Orlando", "Sacramento", "Tampa", "Washington"]

In [3]:
print("The name of all cities that are available to fly to are \n")
# creating a for loop to list all the cities
for city in cities_list:
    print(f"{city}")

The name of all cities that are available to fly to are 

Atlanta
Baltimore
Boston
Charlotte
Dallas
Denver
Miami
Minneapolis
Orlando
Sacramento
Tampa
Washington


### D) (4 points) Check if the input start and target cities are among the cities the traveler is allowed to travel to/from. If not, print an error statement that asks them to input another, appropriate city.

In [9]:
#if else statement taking into account the user input to see if the start city is on the list

if start_city in cities_list:
    print('Yes, your city is on the list.')
    
else:
    print('Your city is not on the list please enter a new one.\n')
    start_city = input("\nEnter new city to start from: ").capitalize()


Yes, your city is on the list.


In [10]:
#if else statement taking into account the user input to see if the start city is on the list

if start_city in cities_list:
    print('Yes, your city is on the list.')
    
else:
    print('Your city is not on the list please enter a new one.\n')
    start_city = input("\nEnter new city to start from: ").capitalize()

Yes, your city is on the list.


In [11]:
#if else statement taking into account the user input to see if the target city is on the list

if target_city in cities_list:
    print('Yes, your city is on the list.')
    
else:
    print('Your city is not on the list please enter a new one.\n')
    target_city = input("\nEnter the city name where you want to reach:").capitalize()

Yes, your city is on the list.


### E)	(4 points) Test that your code so far works. Run it with a start city: Paris and end city: Orlando. When the code complains for your start city, give new start city: Atlanta. Make a screenshot of your test and save it with the appropriate name to your Midterm folder. 

In [12]:
print('completed')

completed


## -----------------------------
## Problem 3 (20 points total).

### A) (3 points) From *Webcourses/Files/Midterm project*  get file “distances_midterm.dat”. This file contains the total distance on the route between city A and B. If you open the file, you will see that it contains a 12 x 12 table (as we have 12 cities we can travel between) with the distances between cities. The $i^{th}$ line and $i^{th}$ column are a given city, so that the diagonal is 0s (as the distance from A to A is zero). The distance between Atlanta and Baltimore, e.g., is 678 miles so that line 0 (#5 of the file) column 1 of your data (i.e., the distance from Atlanta to Baltimore) is 678 (note that the same is true for line 1 [-Baltimore], column 0[-Atlanta] as this is the distance from Baltimore to Atlanta). Use the appropriate numpy function to read the data into variable *travel_data*.

In [4]:
cities_list = ["Atlanta", "Baltimore", "Boston", "Charlotte", "Dallas", "Denver", "Miami", "Minneapolis", "Orlando", "Sacramento", "Tampa", "Washington"]

In [9]:
travel_data = np.genfromtxt('distances_midterm.dat')

In [15]:
print(travel_data)

[[   0.  678. 1094.  245.  782. 1402.  662. 1127.  438. 2467.  467.  638.]
 [ 678.    0.  400.  422. 1366. 1633. 1103. 1109.  983. 2730.  941.   39.]
 [1094.  400.    0.  839. 1761. 1969. 1497. 1390. 1381. 3008. 1341.  439.]
 [ 245.  422.  839.    0. 1026. 1562.  735. 1180.  524. 2676.  580.  399.]
 [ 782. 1366. 1761. 1026.    0.  785. 1313.  991. 1092. 1726. 1107. 1328.]
 [1402. 1633. 1969. 1562.  785.    0. 2064.  914. 1843. 1162. 1857. 1661.]
 [ 662. 1103. 1497.  735. 1313. 2064.    0. 1773.  237. 3039.  270. 1158.]
 [1127. 1109. 1390. 1180.  991.  914. 1773.    0. 1568. 1887. 1583. 1108.]
 [ 438.  983. 1381.  524. 1092. 1843.  237. 1568.    0. 2810.   84.  846.]
 [2467. 2730. 3008. 2676. 1726. 1162. 3039. 1887. 2810.    0. 2832. 2728.]
 [ 467.  941. 1341.  580. 1107. 1857.  270. 1583.   84. 2832.    0.  903.]
 [ 638.   39.  439.  390. 1328. 1661. 1158. 1108.  846. 2728.  903.    0.]]


### B) (4 points) Find which cities the traveler wants to travel from/ to. Use your preferred method to get the index of the cities (assign to variables *first_city* and *second_city*) from your list. 

In [16]:
start_city = input("\nEnter the City where you want to start your trip from:").capitalize()
target_city = input("\nEnter the city name where you want to reach:").capitalize()

first_city = cities_list.index(start_city)
second_city = cities_list.index(target_city)


Enter the City where you want to start your trip from:Orlando

Enter the city name where you want to reach:Denver


### C) (4 points) Using the *travel_data* and indexes *first_city* and *second_city*, find the distance the traveler will travel. Print an informative statement to let the driver know what the distance between their start and end city are.

In [17]:
distance = travel_data[first_city][second_city]
print(f"The distance from {start_city} and {target_city} is:", distance,"miles")

The distance from Orlando and Denver is: 1843.0 miles


### D) (5 points) Assume that the traveler can travel at an average speed of 75mph. Calculate the average travel time it will take them to go from their start_city to their target_city. Calculate how many days ( *travel_time_days* ), hours ( *travel_time_hours* ) and minutes ( *travel_time_minutes* ) the trip will take. Print an informative statement that lets the traveler know how long their trip will be in days, hours and minutes.

In [18]:
t_hours = distance/75
rnd_hours = np.floor(t_hours)

t_minutes = t_hours - rnd_hours
minutes = t_minutes*60
rnd_minutes = np.floor(minutes)

t_days = t_hours/24
rnd_days = np.floor(t_days)

travel_time_days = rnd_days
travel_time_hours = rnd_hours
travel_time_minutes = rnd_minutes

if travel_time_hours >=24:
    travel_time_hours = travel_time_hours - 24
    
print("The Time of your trip is", travel_time_days, "days", travel_time_hours, "hours and", travel_time_minutes, "minutes.")

The Time of your trip is 1.0 days 0.0 hours and 34.0 minutes.


### E) (2 points) Test that your program so far works. Run it from the start_city: Tampa to target_city : Orlando. Your trip should take 1hr and some minutes (note that our assumed average speed is higher than the legal speed limit, so you will get there faster than what, e.g., Google maps suggests). 

In [19]:
print("completed above")

completed above


In [20]:
#Screenshot shows test

### F) (2 points) Turn the program into a function that takes as input a list of the two cities (start, target) and outputs the necessary information (distance, time..). Make sure you include an appropriate informative docstring!

In [21]:
def city_func(cities_list):
    """Input: Start city and target city
       Output: Time and distance between the two cities"""
    
    #index code
    first_city = cities_list.index(start_city)
    second_city = cities_list.index(target_city)
    
    
    #distance code
    t_hours = distance/75
    rnd_hours = np.floor(t_hours)

    t_minutes = t_hours - rnd_hours
    minutes = t_minutes*60
    rnd_minutes = np.floor(minutes)

    t_days = t_hours/24
    rnd_days = np.floor(t_days)

    travel_time_days = rnd_days
    travel_time_hours = rnd_hours
    travel_time_minutes = rnd_minutes

    if travel_time_hours >=24:
        travel_time_hours = travel_time_hours - 24
    
    print("The Time of your trip is", travel_time_days, "days", travel_time_hours, "hours and", travel_time_minutes, "minutes.")
    
    return

cities_list = ["Atlanta", "Baltimore", "Boston", "Charlotte", "Dallas", "Denver", "Miami" "Minneapolis", "Orlando", "Sacramento", "Tampa", "Washington"]

cities_list.append([start_city,target_city])

## -----------------------------
## Problem 4 (15 points total).

### We will now change the existing program to add an extra city as a pitstop.  Let’s make a cross-country road trip from Boston to Sacramento via Denver. Modify your Problem 3 code and function as follows: 



### A) (2 points)  We will now ask the input *start_city*, a *pitstop_city* and a *target_city* for the trip. 

In [41]:
start_city = input("\nEnter the City where you want to start your trip from:").capitalize()
pitstop_city = input("\nEnter the City where you want to make a pitstop:").capitalize()
target_city = input("\nEnter the city name where you want to reach:").capitalize()

first_city = cities_list.index(start_city)
second_city = cities_list.index(target_city)
third_city = cities_list.index(pitstop_city)


Enter the City where you want to start your trip from:Denver

Enter the City where you want to make a pitstop:Washington

Enter the city name where you want to reach:Atlanta


In [42]:
distance = travel_data[first_city][third_city]
dis = travel_data[third_city][second_city]
print(f"The distance from {start_city} and {pitstop_city} is:", distance,"miles." f"The distance from {pitstop_city} and {target_city} is:",dis)

The distance from Denver and Washington is: 1661.0 miles.The distance from Washington and Atlanta is: 638.0


### B) (2 points) Update your function to find which cities the traveler wants to travel from, pitstop at, and go to in your list of cities. Use your preferred method to get the index of the cities (first_city, second_city and third_city) from your list. 

In [43]:
def city_fun(cities_list):
    """Input: Start city, pitstop city and target city
       Output: Time and distance between the three cities"""
    
    #index code
    first_city = cities_list.index(start_city)
    third_city = cities_list.index(pitstop_city)
    second_city = cities_list.index(target_city)
    
    
    #time code
    t_hours = distance/75
    rnd_hours = np.floor(t_hours)

    t_minutes = t_hours - rnd_hours
    minutes = t_minutes*60
    rnd_minutes = np.floor(minutes)

    t_days = t_hours/24
    rnd_days = np.floor(t_days)
    
    #time code for stop to target
    
    total_hours = dis/75
    round_hours = np.floor(total_hours)
    
    total_minutes = total_hours - round_hours
    Min = total_minutes*60
    round_minutes = np.floor(Min)
    
    total_days = total_hours/24
    round_days = np.floor(total_days)
    

    travel_time_days = rnd_days + round_days
    travel_time_hours = rnd_hours + round_hours
    travel_time_minutes = rnd_minutes + round_minutes

    if travel_time_hours >=24:
        travel_time_hours = travel_time_hours - 24
        
    print("The Time of your trip is", travel_time_days, "days", travel_time_hours, "hours and", travel_time_minutes, "minutes.")
    
    return

cities_list = ["Atlanta", "Baltimore", "Boston", "Charlotte", "Dallas", "Denver", "Miami", "Minneapolis", "Orlando", "Sacramento", "Tampa", "Washington"]

cities_list.append([start_city,pitstop_city,target_city])

In [44]:
print(city_fun(cities_list))

The Time of your trip is 0.0 days 6.0 hours and 38.0 minutes.
None


### C) (4 points) Use the above indices and your travel_data to find the distance between first_city - second_city and second_city-third_city. Assuming that your traveler’s car can do 24.9 mpg on the highway and their tank holds 16gallons, calculate how many refueling stops they will need to do on the first and the second leg of their trip Assume that you start the trip with a full tank and round the numbers (e.g., needing 3.2 stops doesn’t make sense). Print an informative statement that lets the traveler know how many stops they will need to do on the two legs of their trip.

### D) (4 points) Assume an average price of $2.4 per gallon and calculate how much the trip will cost in fuel. Print an informative statement that lets the traveler know the total (gas-only) value of their trip. 

### E) (3 points) Did it all work? Run the code for start_city: Boston, pitstop_city: Denver and target_city: Sacramento. 

## -----------------------------
## Problem 5 (20 points total) 

### Let’s try to do a basic navigation code using all our previous parts.

### A) (3 points) Adapt the code by again asking the traveler to only give you a start city and destination city. You will need to then adapt the function from Problem 4 as follows:

### B) (15 points total) The basis of a navigation program is to get your from A to B in the shortest distance/time possible. Let’s try to do this! 

### 1. (3 points) Get the indexes of the cities you start from (start_city) and want to end at (second_city). 

### 2. (10 points) You now need to scan the travel_data table to find the right pitstop city that takes you from A to B in the minimum total distance. Make sure that the straight A to B option is not taken into account, as we need to do a pitstop in some city C. Scan all possible combinations A-->C,C-->B and keep the index (min_tot_dist_ind) of pitstop city C that minimizes the total distance (A-->C) + (C-->B). Print an informative statement that lets the traveler know that they will need to stop in city C, and what the total distance traveled will be. 

### 3. (2 points) Run this program for a trip from Baltimore to Orlando. What is your pitstop city?

### 4. (2 points) Change your function to let the traveler know where they will need to stop, how many stops for gas they will need to do in every leg of the trip and how much the total gas cost of the trip will be. Run it for a trip from Baltimore to Orlando.

## -----------------------------
## Problem 6 (10 points) 

### Prepare and submit your homework. Write what you did to make and submit the zip file into your log. Don’t forget to commit your finalized code and push it to GitHub. When satisfied, close the log, copy it to your homework directory one last time, and run the commands to make and submit the zip file. Turn the file in on WebCourses. 