# FOR, IF, WHILE practicum

<img src="for_loop_flowchart.png" width=600 height=500 />

#### --------------------------

<img src="if_while_flowchart.png" width=600 height=500 />

#### --------------------------

### Examples for syntax:

In [24]:
x = [ 'Mary', 'Poppins', 'was', 'published', 'in', '1934' ]

for word in x:
    print( word )

Mary
Poppins
was
published
in
1934


In [9]:
# or: 
for word in range( len( x ) ):
    print( x[ word ] )

Mary
Poppins
was
published
in
1934


In [11]:
numbers = [ 1, 38, 500, 8, 10, 12, 200, 42 ]

In [13]:
for n in numbers:
    if n > 100:
        print( 'number larger than 100:', n )
    elif n >30:
        print( 'number larger than 30:', n )
    else:
        print( 'too small number' )

too small number
number larger than 30: 38
number larger than 100: 500
too small number
too small number
too small number
number larger than 100: 200
number larger than 30: 42


In [18]:
#or in a while format:
n = 0

while n < len( numbers):
    if numbers[ n ] > 100:
        print( 'number larger than 100:', numbers[ n ] )
    elif numbers[ n ] >30:
        print( 'number larger than 30:', numbers[ n ] )
    else:
        print( 'too small number' )
    n = n + 1

too small number
number larger than 30: 38
number larger than 100: 500
too small number
too small number
too small number
number larger than 100: 200
number larger than 30: 42


In [25]:
m = 1000

while m > 100: 
    m = input( 'Give me a number please' )
    m = float( m )
else:
    print('Your number was too small!')

Give me a number please200
Give me a number please490
Give me a number please30
Your number was too small!


## Let's practice what we learned about FOR/IF/WHILE

#### Let's start by importin numpy, and matplotlib.pyplot

In [26]:
import numpy as np
import matplotlib.pyplot as plt

### 1. Get array z and use a for/else loop that searches z element by element to find the minimum of the full array. How else can you do this? 

In [27]:
z =  np.array( [ 95, 402, 984, 651, 69, 408, 319, 601, 485, 980, 507, 725, 
     547, 544, 610, 83, 165, 141, 500, 263, 17, 865, 575, 219, 390, 984, 
     592, 236, 105, 942, 941, 86, 42, 47, 1, 900, 34, 23, 35, 820, 66, 597, 
     978, 328, 615, 953, 345, 409, 162, 758, 219, 918, 237, 412, 506, 826, 
     248, 86, 950, 626, 949, 687, 217, 815, 67, 104, 58, 512, 24, 892, 894, 
     767, 553, 81, 2379, 843, 831, 445, 742, 717, 958, 609, 842, 451, 688, 
     753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470, 743, 52 ] )

In [1]:
#how else would you do it?


### Do the same thing, but now for the maximum:

### 2. Read in the file first_data_plot.dat that we used in a previous demo. Skip the first line when reading in, it’s a comment line (use comments=‘#’ or skiprows=1). 
 - Print the length of the table. 
 - The first column is the wavelength of your observations, and the other two are two spectra. Make a loop that scans both full spectra and prints the wavelength, and both spectra if the first spectrum is larger than 0.5 and (at the same wavelength) the second one is larger than 0.3. 
 - Print a message warning you that the conditions are not met otherwise.

In [36]:
# read the data in:


[[1.1  0.72 0.75]
 [1.11 0.73 0.7 ]
 [1.11 0.69 0.65]
 [1.11 0.68 0.62]]


In [38]:
# assign to variables with names that make sense:


### 3. Create a variable N and set it equal to 10,000, and a variable m and set it equal to 0.1. Create an array x that goes from 0.1 to N in steps of m.Create an array y that is the natural logarithm of x. Create a for loop that scans all elements of y, prints their value and adds 10.0 to that element. How else could you do this? Which way is faster?

### 4. Now set N=10 and m=1. Create a for loop that plots x,y using a different color for every (x[i],y[i]) set and a different marker (no lines). You can use, e.g., <symb_colors>= red, blue, forestgreen, magenta, brown, black, gray, darkorange, yellow, green (remember color names should be called as ‘red’ ) and <symb_markers> = D, o, p, s, d, P, >, v, <, x

In [51]:
mark_colors = [ 'red', 'blue', 'forestgreen', 'magenta', 'brown', 'black', 'gray', 'darkorange', 'yellow', 'green' ]
mark_syms  = [ 'D', 'o', 'p', 's', 'd', 'P', '>', 'v', '<', 'x' ]

In [2]:
# we need to start by setting up the plot:



### 5. Create an array m1 with numbers 2, 10, 14, 32, 65, 55, 102, 43, 22, 54, 88, 124 and m2 with numbers 9, 32, 6, 88, 65, 100, 77,  40, 21, 54, 124, 61. 
- Scan array m1 and m2 and print the values of m1 that are NOT in m2. 
- Scan arrays m1 and m2 and print the common elements. 
- Scan arrays m1 and m2 and print common elements that are also in the **same** location in the array. 

### 6. Create a list with the names of all months. Create a for loop that goes through the name of the month and the days 1-5 and prints the ‘date'.

### 7. Create a for loop that scans through the elements of the word “Good day” and prints out every letter of the word one at a time. Then a loop that prints every letter up to that iteration (so: G, Go, Goo etc)

In [3]:
# print one letter at a time


In [20]:
#or

In [4]:
# print different number of letters (1, 2, 3,...)



# G
# Go 
# Goo
# Good


In [ ]:
# or you can do it in a while loop:


### 8. Use any loop you like to create a list that contains the Fibonacci series. The Fibonacci series, named after Leonardo Bonacci , is a series of numbers where every number is the sum of the previous two numbers: 0 1 1 2 3 5 8 13 21 34…. Print the first 14 numbers 

In [5]:
# do the fibonnaci series here:


### 9. Create a program that takes as input 4 different numbers and sorts them from smaller to larger:

In [ ]:
#you can google how to get 4 in one go

In [23]:
# sort the numbers   

### 10. Write a code that asks for a month of the year (by name) and prints the maximum number of days in the month. 

### 11. Now write that loop to ask continuously for a month of the year numerically (1, 2, 3,...) and then print the maximum number of dates in the month. If the month number you put is 13 or greater the code crashes with an error message

### 12. The following problem may take some extra time. Use pen and paper if needed, to visualize the problem you are trying to solve. Create a python loop (or combinations of) that will construct the following:

<img src="pyramid_01.png" width=200 height=200 />

#### (note that the problem is easier if you don’t use spaces between the numbers, I used them for better visibility here).

### 13. Let's make boxes with sides x, y, z and calculate their volume. 
- Create array x that is a range from 0.1 to 10 with a step of 0.2. 
- Make array y that is a linspace from 0.1 to 10 in 50 steps. 
- Then make array z that is equal to $x^2 + y^{0.3}$. 
- Calculate the volume of the boxes [assume it is in cu ft ] with every possible combinations of x, y, z. What is the maximum, minimum and mean volume of our boxes in ? If I need boxes with a volume more than 8000 cu ft, how many boxes will I have?

### 14. Create a numpy array z that has the elements: 95, 402, 984, 651, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544, 610, 83, 165, 141, 500, 263, 17, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941, 86, 42, 47, 1, 900, 34, 23, 35, 820, 66, 597, 978, 328, 615, 953, 345, 409, 162, 758, 219, 918, 237, 412, 506, 826, 248, 86, 950, 626, 949, 687, 217, 815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 2379, 843, 831, 445, 742, 717, 958, 609, 842, 451, 688, 753, 854, 685, 93, 1857, 440, 380, 126, 721, 328, 753, 470, 743, 52. 
- Create a for loop that scans through z and prints a ‘yes’ and the element number if z[i] is greater than 200. 
- Change the loop to print a ‘yes’ and the value of z if z[i] is greater than 200 and less than 800. 
- Change the loop to print ‘yes’ and the value of z if z[i] is greater than 200 and less  than 800, but **not** when 220<z[i]<300.
- Create a for/if loop that scans through the elements of z and creates a list with the location i where z[i] is greater than 200. How else could you do this? Which way is faster? 

### 14. We have three dictionaries with the names, HW, quiz and project grades of three students. Scan the grades of each student and if they have a grade <5.5 print a warning sign that the student failed the hw/quiz/project. Start by checking whether the key is the name, if so skip. If the key is not the 'name', scan all grades and print a warning message if the student failed a task. 


### Calculate the average grade of each category for each student and store them in three lists. In a single plot, plot the averages grades of all students for each category .  The x-axis should have as tick labels the names of the categories ('HW', 'Quiz', 'Project').  Use different symbols for each category: e.g, homework == 'o' , quiz == 'd', projects == 's'  and different colors for each student: e.g., black, red, blue

In [ ]:
#We have a dictionary of students (1,2 and 3). For every student we have a name, and their scores (0-10) 
#in hw assignments, quizzes and projects:

student1 = {
  "name": "Jane",
  "homework": [9.0,7.0,5.0,10.],
  "quizzes": [8.0,7.0,9.0],
  "projects": [7.5,9.5]
}
student2 = {
  "name": "Joe",
  "homework": [10.0, 3.9, 4.0, 10.0],
  "quizzes": [5.1, 4.2, 5.0],
  "projects": [8.9, 2.7]
}
student3 = {
  "name": "Jimmy",
  "homework": [3.0, 8.0, 9.0, 10.0],
  "quizzes": [3.0, 7.5, 7.],
  "projects": [8.0, 10.0]
}
